---
sudo: required

env:
  - distribution: debian
    version: stretch
  - distribution: debian
    version: jessie

services:
  - docker


language: python

python:
  - "3.5"
# command to install dependencies
before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'
  - cd src
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python tests/test-app.py
  - cd  ..
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/my_role:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/my_role/setInfrared.yml -i /etc/ansible/roles/my_role/travis/inventory.ini --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/my_role/setInfrared.yml -i /etc/ansible/roles/my_role/travis/inventory.ini'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/my_role/setInfrared.yml -i /etc/ansible/roles/my_role/travis/inventory.ini
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'
