---
- hosts: webserver
  become: true
  tasks:
    - name: define directory
      file:
        path: /opt/web-infrared/
        state: directory
        mode: 0755
    - name: find src 
      shell: find src/* -path 'src/venv/*' -prune -o -path '*/__pycache__/*'  -o -print | grep -v '/venv$' | grep -v '/__pycache__$'
      register: sources
      delegate_to: localhost
      become: false
      changed_when: false

    - name: copy sources
      copy:
        src: "{{ item }}" 
        dest: "/opt/web-infrared/{{ item|regex_replace('^src\\/', '') }}"
      with_items: "{{ sources.stdout_lines }}"

