---
- hosts: webserver
  become: true
  tasks:
    - name: define directory
      file:
        path: /opt/web-infrared/
        state: directory
        mode: 0755

    - name: find src 
      shell: find src/* -path 'src/venv/*' -prune -o -path '*/__pycache__/*'  -o -type f -print | grep -v '/venv$' | grep -v '/__pycache__$'
      register: source_files
      delegate_to: localhost
      become: false
      changed_when: false

    - name: find src 
      shell: find src/* -path 'src/venv/*' -prune -o -path '*/__pycache__/*'  -o -type d -print | grep -v '/venv$' | grep -v '/__pycache__$'
      register: source_dirs
      delegate_to: localhost
      become: false
      changed_when: false

    - name: normalization
      set_fact:
        norm_source_files: "{{ source_files.stdout_lines | map('regex_replace', '^src/', '/opt/web-infrared/') | list }}"
        norm_source_dirs: "{{ source_dirs.stdout_lines | map('regex_replace', '^src/', '/opt/web-infrared/') | list }}"

    - name: create directory
      file:
        state: directory
        path: "/opt/web-infrared/{{ item|regex_replace('^src\\/', '') }}"
      with_items: "{{ source_dirs.stdout_lines }}"

    - name: copy sources
      copy:
        src: "{{ item }}" 
        dest: "/opt/web-infrared/{{ item|regex_replace('^src\\/', '') }}"
      with_items: "{{ source_files.stdout_lines }}"

    - name: find src 
      shell: find /opt/web-infrared/* -path '*/venv/*' -prune -o -path '*/__pycache__/*'  -o -type f -print | grep -v '/venv$' | grep -v '/__pycache__$'
      register: destination_files
      changed_when: false

    - name: debug
      debug:
        var: norm_source_files

    - name: Delete all old files
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ destination_files.stdout_lines }}"
      when: item not in norm_source_files
