FROM debian:stretch

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    software-properties-common \
    python3.5 \
    python3-virtualenv \
    systemd \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ['/bin/systemd']
