FROM debian:stretch

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    software-properties-common \
    python3.5 \
    python3-virtualenv \
    systemd \
 && apt-get clean 

ENTRYPOINT ["/bin/systemd"]
